spring:
  application:
    name: finance

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update # Opções: update, create, validate, none
    show-sql: true # Mostra as queries no console (bom para debug)
    properties:
      hibernate:
        format_sql: true

server:
  # O Railway injeta a variável PORT. Isso é CRUCIAL.
  port: ${PORT:8080}