spring:
  application:
    name: finance

  datasource:
    url: ${DB_URL}.
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Opções: update, create, validate, none
    show-sql: true # Mostra as queries no console (bom para debug)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
